#!/bin/bash

# The plutus-apps repository should be in the same directory as the plutus-pioneer-program repository
# You should execute this script in a 'week' directory. (e.g. week01)

# This script will do the basic setup:
# - get the commit hash from the cabal.project file
# - do the git checkout in the plutus-apps repository
# - enter a nix shell
# - navigate back to plutus-pioneer-program/code/week..

# Get the name of the directory which you are in when executing this script
# (should be week..)
WEEK_DIR=${PWD##*/}

# check if you are in the correct directory
if [[ ${WEEK_DIR} =~ ^week[0-9][0-9]$ ]]; then

    # get the hash message from the cabal.project file
    HASH=$(cat cabal.project | grep -A 1 "location: https://github.com/input-output-hk/plutus-apps.git" | cut -f 4 -d " " | tail -n 1)

    # navigate to plutus-apps folder
    cd ../../../plutus-apps

    # check if the navigation succeeded
    CURRENT_DIR=${PWD##*/}
    if [ "${CURRENT_DIR}" = "plutus-apps" ]; then 
        # do the checkout
        git checkout ${HASH}
        # enter nix-shell and navigate back to the week directory when entered
        nix-shell --command "cd ../plutus-pioneer-program/code/${WEEK_DIR}; return"

# Error messages

    else
        echo "The plutus-apps repository should be in the same directory as the plutus-pioneer-program repository"
    fi
else
    echo "You should execute this script in a 'week' directory. (e.g. week01)"
fi
